version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: c4i-web
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./deployments/webapps:/var/lib/jetty/webapps
      - ./deployments/log:/var/log/jetty